version: '3.8'

services:
  # Redis service
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    networks:
      - recruiterbook-network

  # Uncomment this section to run the API service in Docker
  # api:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DATABASE_URL=${DATABASE_URL}
  #     - REDIS_URL=redis://redis:6379
  #     - OPENAI_API_KEY=${OPENAI_API_KEY}
  #     - ENVIRONMENT=${ENVIRONMENT:-dev}
  #     - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  #   depends_on:
  #     - redis
  #   networks:
  #     - recruiterbook-network
  #   restart: unless-stopped

volumes:
  redis_data:

networks:
  recruiterbook-network:
    driver: bridge 